from django.urls import path

from main_app.EditResultView import EditResultView

from . import hod_views, parent_views, staff_views, student_views, views

urlpatterns = [
    path("", views.login_page, name='login_page'),
    path("get_attendance", views.get_attendance, name='get_attendance'),
    path("doLogin/", views.doLogin, name='user_login'),
    path("logout_user/", views.logout_user, name='user_logout'),

    path("admin/home/", hod_views.admin_home, name='admin_home'),
    path("admin/view/profile/", hod_views.admin_view_profile, name='admin_view_profile'),
    path("attendance/view/", hod_views.admin_view_attendance, name="admin_view_attendance"),
    path("result/semester/add/", hod_views.admin_add_semester_result, name="admin_add_semester_result"),
    path("result/semester/add_from_xlsx/", hod_views.add_semester_results_from_xlsx, name="add_semester_results_from_xlsx"),
    path("notifications/", hod_views.admin_notifications, name="admin_notifications"),
    path("feedbacks/", hod_views.admin_feedbacks, name="admin_feedbacks"),
    path("leaves/", hod_views.admin_leaves, name="admin_leaves"),
    path("attendance/fetch/", hod_views.get_admin_attendance, name='get_admin_attendance'),
    path("check_email_availability", hod_views.check_email_availability, name="check_email_availability"),

    path("staff/add", hod_views.add_staff, name='add_staff'),
    path("staff/add_from_xlsx/", hod_views.add_staff_from_xlsx, name="add_staff_from_xlsx"),
    path("staff/manage/", hod_views.manage_staff, name='manage_staff'),
    path("staff/edit/<int:staff_id>", hod_views.edit_staff, name='edit_staff'),
    path("staff/delete/<int:staff_id>", hod_views.delete_staff, name='delete_staff'),
    path("staff/delete-all/", hod_views.delete_all_staff, name='delete_all_staff'),
    path("staff/view/feedback/", hod_views.staff_feedback_message, name="staff_feedback_message"),
    path("staff/view/leave/", hod_views.view_staff_leave, name="view_staff_leave"),

    path("student/add/", hod_views.add_student, name='add_student'),
    path("students/add_from_xlsx/", hod_views.add_students_from_xlsx, name='add_students_from_xlsx'),
    path("parents/add_from_xlsx/", hod_views.add_parents_from_xlsx, name='add_parents_from_xlsx'),
    path("student/manage/", hod_views.manage_student, name='manage_student'),
    path("student/edit/<int:student_id>", hod_views.edit_student, name='edit_student'),
    path("student/delete/<int:student_id>", hod_views.delete_student, name='delete_student'),
    path("student/delete-all/", hod_views.delete_all_students, name='delete_all_students'),
    path("student/view/feedback/", hod_views.student_feedback_message, name="student_feedback_message"),
    path("student/view/leave/", hod_views.view_student_leave, name="view_student_leave"),
    path("student/detail/<int:student_id>/", hod_views.student_detail, name='student_detail'),
    path("student/suspend/<int:student_id>/", hod_views.toggle_student_suspension, name='toggle_student_suspension'),

    path("add-parent/", hod_views.add_parent, name='add_parent'),
    path("parent/manage/", hod_views.manage_parent, name='manage_parent'),
    path("parent/edit/<int:parent_id>/", hod_views.edit_parent, name='edit_parent'),
    path("parent/delete/<int:parent_id>/", hod_views.delete_parent, name='delete_parent'),
    path("parent/delete-all/", hod_views.delete_all_parents, name='delete_all_parents'),
    path("student/by-roll-number/", hod_views.get_student_by_roll_number, name='get_student_by_roll_number'),
    path("hod/parent_feedback/", hod_views.parent_feedback_message, name='parent_feedback_message'),
    path("send-parent-notification/", hod_views.send_parent_notification, name='send_parent_notification'),
    path("send-parent-notification/all/", hod_views.send_parent_notification_to_all, name='send_parent_notification_to_all'),

    path("course/add", hod_views.add_course, name='add_course'),
    path("course/manage/", hod_views.manage_course, name='manage_course'),
    path("course/edit/<int:course_id>", hod_views.edit_course, name='edit_course'),
    path("course/delete/<int:course_id>", hod_views.delete_course, name='delete_course'),

    path("subject/add/", hod_views.add_subject, name='add_subject'),
    path("subject/manage/", hod_views.manage_subject, name='manage_subject'),
    path("subject/edit/<int:subject_id>", hod_views.edit_subject, name='edit_subject'),
    path("subject/delete/<int:subject_id>", hod_views.delete_subject, name='delete_subject'),

    path("add_session/", hod_views.add_session, name='add_session'),
    path("session/manage/", hod_views.manage_session, name='manage_session'),
    path("session/edit/<int:session_id>", hod_views.edit_session, name='edit_session'),
    path("session/delete/<int:session_id>", hod_views.delete_session, name='delete_session'),

    path("send_student_notification/", hod_views.send_student_notification, name='send_student_notification'),
    path("send_staff_notification/", hod_views.send_staff_notification, name='send_staff_notification'),
    path("send-notification/everyone/", hod_views.send_notification_to_everyone, name='send_notification_to_everyone'),
    path("send_student_notification/all/", hod_views.send_student_notification_to_all, name='send_student_notification_to_all'),
    path("send_staff_notification/all/", hod_views.send_staff_notification_to_all, name='send_staff_notification_to_all'),

    path("staff/home/", staff_views.staff_home, name='staff_home'),
    path("staff/apply/leave/", staff_views.staff_apply_leave, name='staff_apply_leave'),
    path("staff/feedback/", staff_views.staff_feedback, name='staff_feedback'),
    path("staff/view/profile/", staff_views.staff_view_profile, name='staff_view_profile'),
    path("staff/attendance/take/", staff_views.staff_take_attendance, name='staff_take_attendance'),
    path("staff/attendance/update/", staff_views.staff_update_attendance, name='staff_update_attendance'),
    path("staff/get_students/", staff_views.get_students, name='get_students'),
    path("staff/attendance/fetch/", staff_views.get_student_attendance, name='get_student_attendance'),
    path("staff/attendance/save/", staff_views.save_attendance, name='save_attendance'),
    path("staff/attendance/update/save/", staff_views.update_attendance, name='update_attendance'),
    path("staff/view/notification/", staff_views.staff_view_notification, name="staff_view_notification"),
    path("staff/notifications/", staff_views.staff_notifications, name='staff_notifications'),
    path("staff/leave/substitute/<int:leave_id>/<str:response>/", staff_views.staff_respond_leave_substitution, name="staff_respond_leave_substitution"),
    path("staff/notifications/clear/", staff_views.staff_clear_notifications, name='staff_clear_notifications'),
    path("staff/send/student/notification/", staff_views.staff_send_student_notification, name='staff_send_student_notification'),
    path("staff/send/student/notification/all/", staff_views.staff_send_student_notification_to_all, name='staff_send_student_notification_to_all'),
    path("staff/send/parent/notification/", staff_views.staff_send_parent_notification, name='staff_send_parent_notification'),
    path("staff/send/parent/notification/all/", staff_views.staff_send_parent_notification_to_all, name='staff_send_parent_notification_to_all'),
    path("staff/send/notification/everyone/", staff_views.staff_send_notification_to_everyone, name='staff_send_notification_to_everyone'),
    path("staff/result/add/", staff_views.staff_add_result, name='staff_add_result'),
    path("staff/result/edit/", EditResultView.as_view(), name='edit_student_result'),
    path("staff/result/fetch/", staff_views.fetch_student_result, name='fetch_student_result'),

    path("student/home/", student_views.student_home, name='student_home'),
    path("student/view/attendance/", student_views.student_view_attendance, name='student_view_attendance'),
    path("student/apply/leave/", student_views.student_apply_leave, name='student_apply_leave'),
    path("student/feedback/", student_views.student_feedback, name='student_feedback'),
    path("student/view/profile/", student_views.student_view_profile, name='student_view_profile'),
    path("student/view/notification/", student_views.student_view_notification, name="student_view_notification"),
    path("student/notifications/clear/", student_views.student_clear_notifications, name='student_clear_notifications'),
    path('student/view/result/', student_views.student_view_result, name='student_view_result'),
    path('student/view/semester-result/', student_views.student_view_semester_result, name='student_view_semester_result'),

    path('parent/home/', parent_views.parent_home, name='parent_home'),
    path('parent/profile/', parent_views.parent_view_profile, name='parent_view_profile'),
    path('parent/notifications/', parent_views.parent_view_notification, name='parent_view_notification'),
    path('parent/notifications/clear/', parent_views.parent_clear_notifications, name='parent_clear_notifications'),
    path('parent/feedback/', parent_views.parent_feedback, name='parent_feedback'),
]
