# Generated by Django 5.1 on 2024-11-18 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_message_hod_parent_notificationparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.parent')),
            ],
        ),
        migrations.DeleteModel(
            name='Message_HOD',
        ),
    ]
