# Generated by Django 3.2.25 on 2025-04-03 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_customuser_roll_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='roll_number',
        ),
    ]
